-- MySQL Script generated by MySQL Workbench
-- Wed Apr 19 15:42:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EscoladeMusicaSilasCando
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EscoladeMusicaSilasCando
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EscoladeMusicaSilasCando` DEFAULT CHARACTER SET utf8 ;
USE `EscoladeMusicaSilasCando` ;

-- -----------------------------------------------------
-- Table `EscoladeMusicaSilasCando`.`Orquestra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EscoladeMusicaSilasCando`.`Orquestra` (
  `idOrquestra` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Cidade` VARCHAR(100) NOT NULL,
  `Pais` VARCHAR(60) NOT NULL,
  `Dt_criacao` DATE NULL,
  PRIMARY KEY (`idOrquestra`),
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EscoladeMusicaSilasCando`.`Musico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EscoladeMusicaSilasCando`.`Musico` (
  `idMusico` INT NOT NULL AUTO_INCREMENT,
  `Identidade` VARCHAR(45) NOT NULL,
  `Dt_nascimento` DATE NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Nacionalidade` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idMusico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EscoladeMusicaSilasCando`.`Instrumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EscoladeMusicaSilasCando`.`Instrumento` (
  `IdInstrumento` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`IdInstrumento`));


-- -----------------------------------------------------
-- Table `EscoladeMusicaSilasCando`.`Pertence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EscoladeMusicaSilasCando`.`Pertence` (
  `Musico_idMusico` INT NOT NULL,
  `Orquestra_idOrquestra` INT NOT NULL,
  INDEX `fk_Pertence_Musico1_idx` (`Musico_idMusico` ASC) VISIBLE,
  INDEX `fk_Pertence_Orquestra1_idx` (`Orquestra_idOrquestra` ASC) VISIBLE,
  PRIMARY KEY (`Musico_idMusico`),
  CONSTRAINT `fk_Pertence_Musico1`
    FOREIGN KEY (`Musico_idMusico`)
    REFERENCES `EscoladeMusicaSilasCando`.`Musico` (`idMusico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pertence_Orquestra1`
    FOREIGN KEY (`Orquestra_idOrquestra`)
    REFERENCES `EscoladeMusicaSilasCando`.`Orquestra` (`idOrquestra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EscoladeMusicaSilasCando`.`Toca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EscoladeMusicaSilasCando`.`Toca` (
  `Musico_idMusico` INT NOT NULL,
  `Instrumento_IdInstrumento` INT NOT NULL,
  PRIMARY KEY (`Musico_idMusico`, `Instrumento_IdInstrumento`),
  INDEX `fk_Musico_has_Instrumento_Instrumento1_idx` (`Instrumento_IdInstrumento` ASC) VISIBLE,
  INDEX `fk_Musico_has_Instrumento_Musico1_idx` (`Musico_idMusico` ASC) VISIBLE,
  CONSTRAINT `fk_Musico_has_Instrumento_Musico1`
    FOREIGN KEY (`Musico_idMusico`)
    REFERENCES `EscoladeMusicaSilasCando`.`Musico` (`idMusico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Musico_has_Instrumento_Instrumento1`
    FOREIGN KEY (`Instrumento_IdInstrumento`)
    REFERENCES `EscoladeMusicaSilasCando`.`Instrumento` (`IdInstrumento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EscoladeMusicaSilasCando`.`Sinfonia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EscoladeMusicaSilasCando`.`Sinfonia` (
  `idSinfonia` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Compositor` VARCHAR(100) NOT NULL,
  `Dt_criacao` DATE NOT NULL,
  PRIMARY KEY (`idSinfonia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EscoladeMusicaSilasCando`.`Executa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EscoladeMusicaSilasCando`.`Executa` (
  `Orquestra_idOrquestra` INT NOT NULL,
  `Sinfonia_idSinfonia` INT NOT NULL,
  PRIMARY KEY (`Sinfonia_idSinfonia`, `Orquestra_idOrquestra`),
  INDEX `fk_Orquestra_has_Sinfonia_Sinfonia1_idx` (`Sinfonia_idSinfonia` ASC) VISIBLE,
  INDEX `fk_Orquestra_has_Sinfonia_Orquestra1_idx` (`Orquestra_idOrquestra` ASC) VISIBLE,
  CONSTRAINT `fk_Orquestra_has_Sinfonia_Orquestra1`
    FOREIGN KEY (`Orquestra_idOrquestra`)
    REFERENCES `EscoladeMusicaSilasCando`.`Orquestra` (`idOrquestra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Orquestra_has_Sinfonia_Sinfonia1`
    FOREIGN KEY (`Sinfonia_idSinfonia`)
    REFERENCES `EscoladeMusicaSilasCando`.`Sinfonia` (`idSinfonia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EscoladeMusicaSilasCando`.`Funcao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EscoladeMusicaSilasCando`.`Funcao` (
  `IdFruncao` INT NOT NULL,
  `Nome` VARCHAR(60) NOT NULL,
  `Musico_idMusico` INT NOT NULL,
  PRIMARY KEY (`IdFruncao`),
  INDEX `fk_Funcao_Musico1_idx` USING BTREE (`Musico_idMusico`) VISIBLE,
  CONSTRAINT `fk_Funcao_Musico1`
    FOREIGN KEY (`Musico_idMusico`)
    REFERENCES `EscoladeMusicaSilasCando`.`Musico` (`idMusico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `EscoladeMusicaSilasCando`.`Apresenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EscoladeMusicaSilasCando`.`Apresenta` (
  `Musico_idMusico` INT NOT NULL,
  `Sinfonia_idSinfonia` INT NOT NULL,
  `Funcao_IdFruncao` INT NOT NULL,
  `Dt_apresentacao` DATE NOT NULL,
  PRIMARY KEY (`Musico_idMusico`, `Sinfonia_idSinfonia`, `Funcao_IdFruncao`),
  INDEX `fk_Apresenta_Sinfonia1_idx` (`Sinfonia_idSinfonia` ASC) VISIBLE,
  INDEX `fk_Apresenta_Funcao1_idx` (`Funcao_IdFruncao` ASC) VISIBLE,
  CONSTRAINT `fk_Apresenta_Musico1`
    FOREIGN KEY (`Musico_idMusico`)
    REFERENCES `EscoladeMusicaSilasCando`.`Musico` (`idMusico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Apresenta_Sinfonia1`
    FOREIGN KEY (`Sinfonia_idSinfonia`)
    REFERENCES `EscoladeMusicaSilasCando`.`Sinfonia` (`idSinfonia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Apresenta_Funcao1`
    FOREIGN KEY (`Funcao_IdFruncao`)
    REFERENCES `EscoladeMusicaSilasCando`.`Funcao` (`IdFruncao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- alters e deletes 
alter table funcao
rename column idfruncao to idfuncao;


alter table sinfonia 
modify column nome varchar (180);

alter table instrumento
	ADD grupo varchar (60);
    
alter table apresenta
ADD telefone varchar(15);

alter table apresenta
drop column telefone;

alter table instrumento
drop column grupo;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
SET SQL_SAFE_UPDATES=0;
